### ISSUE TITLE
Advanced Time Control

### ISSUE THREAD

**Issue by Nakel** [pychess/pychess#1015]
At our local chess club, we have switched to PyChess because it is much more convenient, good looking and much smoother than the rugged Arena and other GUI's. We use it for casual lectures and challenges. Our grandmaster, when giving a challenge, is unable to maintain fairness and integrity as PyChess only allows the amount of minutes and increment for each move in a game to be set.

It would be much much better, if PyChess allowed a game to have X minutes for the first Y moves, followed by Z minutes for the rest of the game with an addition of N increment on each move.

**Comment by gbtami** [comment]
Agreed. I like to implement this, #744 and #755 in 0.12.1 after 0.12 final is out.

**Comment by gbtami** [comment]
@Nakel can you explain more the situation please? The "challenge" means  human-engine games or human-human games against your GM using PyChess instead of phisical board? I'm asking this because xboard/uci protocols doesn't support two phase time controls see http://www.talkchess.com/forum/viewtopic.php?t=58199
