### ISSUE TITLE
bug : bottom notification bar cut off in maximized window

### ISSUE THREAD

**Issue by bboutkov** [pychess/pychess#1018]
When analyzing a game the bottom notification bar is cut off.

There is an option to scroll it down a little bit, but using that scroll-bar to see half of the word "abort" is ridiculous. I think there is similar behaviour with other notifications on the bottom, but I dont currently recall which ones pop up down there so I cant test for that.

![cutoff](https://cloud.githubusercontent.com/assets/5230985/10110351/acdf4954-639a-11e5-81e4-491eef39c9ba.png)
![cutoff_2](https://cloud.githubusercontent.com/assets/5230985/10110352/ace7c4b2-639a-11e5-9e7f-51591e6658cb.png)

**Comment by gbtami** [comment]
I think this is caused by #958 fix :(
When game starts there is no infobar widget, there is just a placeholder, without size request. The navigation buttons are fixed size icons. We don't want the board change its size when a new infobar message appears. But if I enable the infobar to request more space, It may draw out of screen. Telling the truth I have no idea how to fix this issue in an elegant way yet.

**Comment by bboutkov** [comment]
A simple fix for now could be  to simply write everything on one line and only wrap to the next line when text is longer than the allowed window size.

Perhaps a more permanent solution involves restructuring the Infobar system be a notification panel similar to chat, which becomes active or blinks for example upon getting a new message such as end of game or someone signing on.

**Comment by gbtami** [comment]
Applied your simple fix suggestion. It should be better now. Can you try it, please?

**Comment by bboutkov** [comment]
yep looks much better! thanks!
