### ISSUE TITLE
When GUEST connections prevented, Player list and Game list not appearing in ICLounge

### ISSUE THREAD

**Issue by cajone** [pychess/pychess#1066]
Can't seem to see a list of either players or games in progress, just getting the spinning wait icon with no update.

I tried typing 'games' in console and got an immediate response and the same for 'players'

(potential bug)

**Comment by gbtami** [comment]
The problem was caused by FICS server disabling guest logins. See "Due to abuse problems, guest connections have been prevented." in .log file. PyChess uses a secondary/helper guest connection to maintain players/games lists setting pin,gin,availinfo variables. Before when we used only one connection setting pin/gin variables caused several user complaints. See #608 
I think we can't change this  until FICS not introduces these as interface variables (instead of user variables).
One thing I noticed we should fix is catching game end messages. They are handled in (guest)helper connection now, so never processed when guest connections are refused. We should move this regexp from ic/HelperManager.py to ic/BoardManager.py

**Comment by gbtami** [comment]
Player list info handling should be moved from HelperConnection to MainConnection as "pin" is interface variable on FICS. "gin" is not, but if we detect that guest login is disabled we should send and process one "games" command on startup and when focus changes to games tab.
