### ISSUE TITLE
Multiple notifications for friends

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1167]
If a friend of mine logs in and out and in and out while I am playing, notifications will stack on each other, being confusing in that it is not clear which is the latest one and what is the friend doing now.

A better system would delete older notifications for the same user, keeping only the most recent ones, or give no notification at all if a friend connects and disconnects [I like this latter _less_].

**Comment by cajone** [comment]
Yes I thought a bit about this a while back ( me being one of the people that logs in and out all day long). I think maybe a way to approach this is instead of all the coming and going events stacking up on top of each other ( you then have to click the close button numerous times ) would be to have a panel that adds events to, but replaces old events of the same type rather than just adding to. ie a player can log in/out  and there would onlt be one panel entry for this event showing the last login/out but that player might login and challenge you that would be 2 events etc.

We then could keep a lamp icon ( notification toggle ) to say an new event has occured that toggles off when the panel is pulled into focus similar to the way the channels work or observed game events work today.

what do you think ?

**Comment by massimiliano-leoni** [comment]
Yes, this is a more elaborate version of what I had in mind. I like that!
