### ISSUE TITLE
Failing preferences storytext usecase

### ISSUE THREAD

**Issue by gbtami** [pychess/pychess#1278]
(To reproduce you have to clone https://github.com/gbtami/storytext first.)
The usecase is simple, just start pychess->edit->preferences then close it and quit.
Recording seems ok, but default config item events recorded before menu activation event and replaying fails.
The relevant files are:
https://github.com/pychess/pychess/blob/master/testing/storytext/preferences
https://github.com/pychess/pychess/blob/master/testing/storytext/prefs_record.txt
https://github.com/pychess/pychess/blob/master/testing/storytext/prefs_replay.txt

**Comment by gjb1002** [comment]
Can you clarify "default config item events recorded before menu activation event"? I don't really understand what this means. What are "default config item events"?

Could you attach the UI map file also? That would make it easier to see what kinds of events are involved.

If you can produce a "cutdown" version of PyChess or a simpler GUI that reproduces the problem that would help me a great deal.

**Comment by gbtami** [comment]
About "default config item events":
The affected code is here: https://github.com/pychess/pychess/blob/master/lib/pychess/widgets/preferencesDialog.py

The pychess->edit->preferences menu starts a dialog (a Gtk.Window) which contains a Gtk.Notebook with some tabs containing checkboxes/dropdowns/etc. Some of these are checked on or selected by the appropriate tab class init method. I referenced these as "default config item events".

As you can see in https://github.com/pychess/pychess/blob/master/testing/storytext/prefs_record.txt all of these events happens before this line:
Recording u'preferences_menu'  

And as the https://github.com/pychess/pychess/blob/master/testing/storytext/prefs_replay.txt shows the dropdown selection can't be performed on replay because the dialog was not initialize it's model yet (the 'preferences menu' event is recorder _after_ dropdown selection event).

The UI map file and everything to replace the problem is here:
https://github.com/pychess/pychess/tree/master/testing/storytext

**Comment by gjb1002** [comment]
Thanks for clarifications.

If you can also create a simplified GUI that reproduces it, that would be best. If not, I'll have a go with PyChess next time I get a moment (probably next week now).

**Comment by gjb1002** [comment]
I had a little look this morning. The problem isn't with replaying but with recording, the recording should not contain anything about all the default values set in the dialog, it should only contain lines for what you as a user do. 

The basic reason seems to be that the entire mechanism to prevent recording when things are programmatically changed seems to not be working. I suspect the gtk3 spike code (which I didn't write myself) did not get this far as I don't think it was applied to anything except toy problems. 

StoryText records by listening for signals, for example the "changed" signal on a gtk.Entry. Of course, this can also be emitted by program code calling "set_text" (or similar), which should not be recorded. StoryText manages this for PyGTK by listing all such programmatic change methods explicitly for each widget, for example in the EntryEvent class (this mechanism I now consider to be somewhat brittle : PyGTK was the first GUI library supported and I chose to handle this differently in the libraries StoryText has supported since.)

In any case, all such listed methods are then monkey-patched whenever such an object is discovered, see for example ProgrammaticChangeIntercept in the guishared module. 

For some reason this mechanism doesn't seem to be kicking in at all in your case. I don't know why this is: either the patching is not working or it is being applied too late. 

That's what I've been able to find out this morning, hope it helps. I can take another look sometime if you can't make progress but this coming week is now looking fairly full.

**Comment by gbtami** [comment]
Thank you very much! I really appreciate your detailed explanation. Regarding "PyGTK was the first GUI library supported and I chose to handle this differently in the libraries StoryText has supported since." don't you think I better to create a new toolkit (gtk3) with the new way you chose for other toolkits later (without using that ugly pygtkcompat)? If yes, can you give me some pointers where should I start please?

**Comment by gjb1002** [comment]
That depends on how much time you have to devote to this :) Starting again with a new toolkit using the lessons learned from the others may well be the cleanest way but it's a substantial piece of development, a man-month or two of work has typically been needed to support something new from scratch.

If you're hoping for something that can be made to work without too much effort I'd say stick with what's there for the moment and try to fiddle and make it work. There may be a simple explanation and fix for why the programmatic change code isn't working.

**Comment by gjb1002** [comment]
I had another look this evening but I'm afraid I can't really make progress with the time I'm prepared to invest :) PyChess is too complicated and it's too long since I did any PyGTK development, and I've never looked at gtk3.

I'm prepared to have another go if you can make a much simpler GUI which demonstrates the problem, or I can answer any questions you might have. Otherwise, I'm done here.

**Comment by gbtami** [comment]
I will definitely try to create a simpler GUI to demonstrate our problem in the near future. Thx anyhow!

**Comment by gbtami** [comment]
Created a self contained example (sample_app.py) demonstrating the problem:
https://gist.github.com/gbtami/5d53b4bf061591f0589c

**Comment by gjb1002** [comment]
Thanks, now I could find the issue much more easily.

The basic problem can be boiled down to this:
set_value = getattr(widget, setter)

Perfectly legal Python of course but as long as StoryText's approach to programmatic changes is to monkey-patch the setters on the widgets as soon as it knows about them (see my previous comment), it won't work to cache the setters locally first. StoryText comes along, patches Entry.set_text quite happily, but you have your own cache of the Entry.set_text method which bypasses StoryText's attempt to handle this.

Unfortunately, the only way to fix this on the StoryText side is to change approach here, and that's a nontrivial task. This is one reason why I chose to do things differently for other toolkits. But I would guess you might be able to find a workaround that doesn't involve local caches of setters, and that would be a lot less trouble.

It's nothing to do with gtk3, in any case :)

**Comment by gbtami** [comment]
Thank you very much! At least I know now where should I change pychess or storytext to let them work together better.
