### ISSUE TITLE
Should most of the plethora of panels be disabled by default?

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#1458]
I submit that at least most of the panels - analysis, hints, etc. - should be disabled by default. I don't know what others think.

**Comment by gbtami** [comment]
Good question. I think different users want different defaults and we should enable by default only panels most of our users like to see. I myself definitely never use Move History, Comments and Engines(output) panels. I will ask this question on http://groups.google.com/group/pychess-people to get some more user feedback.

**Comment by gbtami** [comment]
https://groups.google.com/forum/#!topic/pychess-people/U9W4Sc6k-vw

**Comment by bboutkov** [comment]
I dont know if we should remove working features by default, I would lean towards keeping things as they are but  giving the user more options to hide, and as Cotton mentioned, a cleaner default interface.

I dont really use any of the mentioned extra panels, but currently instead of disabling I just stack all the less common panels underneath the common ones to create a more compact view. For example console/news/talking is all one panel, and move history/comments/engines/etc all are in one panel as well. This creates a cleaner feel to the program and hides some functionality I dont care as much about. Maybe something like this could be a better default for the layout.

In terms of disabling / hiding features, I think an improvement would be to let the user perform all actions from the View menu instead of going through preferences->sidepanels. I think its a  little confusing and inconvenient that some features are only in View while some only in preferences->sidepanels.

**Comment by gbtami** [comment]
@bboutkov your suggestion reminded me to #347 (and reopened it) Thx!

**Comment by gbtami** [comment]
@bboutkov implemented hide/show sidepanel menuitems in View menu. Can you test it please?

**Comment by ghost** [comment]
Sorry, is it me you are asking to test a build of pychess? But in fact for the moment I've gone back to LucasChess (on Linux, via Wine) . . I hope to return to pychess in the future.

**Comment by gbtami** [comment]
@CottonEaster no problem.

**Comment by bboutkov** [comment]
@gbtami Ive been playing around with the new panel enable/disable functionality and things seem to look really good.  I was pleasantly surprised to find that the panels remember their old location history so when reneabled theyre in the same place as they were before;  even when I disable all of the panels at once - nice!

**Comment by gbtami** [comment]
@bboutkov I'm thinking about to remove  preferences->sidepanels. I think it has no additional value now.

**Comment by bboutkov** [comment]
I agree, its much simpler to keep this all in one location both from the code perspective, and from the users. I think most people are used to layout functionalities using the view menu as this is how it works in most guis so I think its enough for our purposes.

**Comment by gbtami** [comment]
Removed.
