### ISSUE TITLE
Bug: last played move of game doesnt always appear

### ISSUE THREAD

**Issue by bboutkov** [pychess/pychess#1462]
Ive noticed that sometimes when getting checkmated the last move doesnt appear on the board (or in the move list) when the game ends and the rematch popup dialog appears. I think this may be another asyncio issue where multiple end-of-game infos are being sent at the same time from  FICS and we dont process them in the proper order so we lose a little bit of information.

**Comment by bboutkov** [comment]
Oh I just saw #1461 and I think this may be related to a very similar situation. Feel free to close this if this is a duplicate - sorry!

**Comment by gbtami** [comment]
Thx for reporting this Boris! I'v seen this also before, just forgot to file here. I think this bug is independent from #1461 In that case an extra style12 message (for the same move!) sent by the server when game ends with forfeit on time, but pychess processes it incorrectly. Here we should have to process latest style12 before game ended messages as you write. Agreed that this is timing/ordering asyncio issue.
