### ISSUE TITLE
Error in argparse

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1490]
Hello,

On Windows only, if you run pyChess with an unknown/misspelled argument in the command line (like `pychess.exe --hello`), you get an error not meaningful for the player :

![image](https://user-images.githubusercontent.com/24614488/32134347-f2e71fb6-bbeb-11e7-916f-e8f88bcc8258.png)

You probably have some liberty to upgrade that package. Else, please find attached a patch but it has an effect : pyChess will *not* stop its own execution if an invalid argument is found. I let you validate that proposal first.

[patch.zip](https://github.com/pychess/pychess/files/1424228/patch.zip)

Regards

**Comment by gbtami** [comment]
The problem is nor unknown/misspelled argument nor argparse package version, but cx_freezee. You can trigger this output with .msi packaged pychess using the correct `--version` argument also. And will never  see it running pychess from sources.

In frozen cx_freezee GUI applications sys.stdout and sys.stderr are both None, but standard python modules like argparse know nothing about this and never use `if sys.stdout is None:` before printing something to sys.stdout. See https://stackoverflow.com/questions/38404800/cx-freeze-doesnt-print-to-console
We redirect them to .log as Anthony Tuininga suggests as you can see at https://github.com/pychess/pychess/blob/master/pychess#L200 but this happens after processing arguments.

There are several ways to fix this.
1. We can try to import and use argparse **after** stdout/stderr redirections.
2. If this doesn't work, we can use your patch.
3. Change from cx_freezee to pynsist http://pynsist.readthedocs.io/en/latest/

This latter makes a Windows installer which installs a version of Python that you specify, and then installs your application. It doesn't try to 'freeze' your application into an exe, but makes shortcuts which launch .py files. This avoids certain kinds of bugs like this one.
I myself prefer 3., just never had time to try how it works.
