### ISSUE TITLE
Sometimes posting of new losers seek fails

### ISSUE THREAD

**Issue by zepler** [pychess/pychess#1567]
Sometimes (but not always) posting of new seek fails. This has only happened on losers games -but I mostly play losers lately so I am not sure on this. Pychess version 0.99.1 on Debian GNU/Linux 9, Stretch (Stable).

The console output is this:
(21:24:33) No such board: w17 0-9999

Announcing the seek with the console command "seek 3 0 losers" still works properly. Also, quitting pychess and starting again mostly works.

**Comment by gbtami** [comment]
It would be good if you can send a .log file containing a session when with this event happens. Start pychess from console with --log-debug to produce verbose .log file in ~/.local/share/pychess please!

**Comment by zepler** [comment]
Here you go.


[2018-01-25_08-17-53.log](https://github.com/pychess/pychess/files/1662758/2018-01-25_08-17-53.log)

**Comment by gbtami** [comment]
Thank you! Seems this regression was caused by adding ICC variant game support because they use different names from FICS sometimes (w22 vs wild/fr and w17 vs losers ). Can you test my latest commit , please? You just have to clone pychess repo with: `git clone https://github.com/pychess/pychess.git`. Then you can run it with `./pychess` in place. If you don't have git installed, `sudo apt install git` first.
