### ISSUE TITLE
Tag editor

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1581]
Hello,

This is a feature request.

Currently, there is no possibility to edit the extra-tags of a game. The idea is to implement a tag editor in string format only in the properties of the game. The checklist could be the following one :

1. Review the layout of gameinfoDialog to use tabs like engineDialog :
    - [x] The main properties of the game (like today)
    - [x] Add a button for `Date` to call a Gtk.Calendar
    - [x] Empty tab for the additional tags
2. Implement the logic of the tag editor :
    - [x] Changeable treeview
    - [x] Load the filtered out tags managed in the first dedicated tab
    - [x] Add tag
    - [x] Remove tag
    - [x] Effective update after pressing the button OK
3. Load the tags from a pasted PGN :
    - [x] Parse the tags in pgn.py `load_game_tags()`
    - [x] The additional tags are parsed but are not exportable because `loadToModel()` doesn't put them to model.tags
    - [x] Allow text highlight for the unconventional tags
4. Load the tags from a PGN database :
    - [x] Parse the tags in PgnImport.py `read_games()`
    - [x] Store the tags
    - [x] Load the tags when `loadToModel()` is called
5. Export to PGN :
    - [x] Static processing (7TR and classic fields from the game)
    - [x] Dynamic processing of the additional tags

Do you see something else to validate or not such an enhancement ?

To start, I can help on the steps 1 and 5.

Regards

**Comment by gbtami** [comment]
Good idea. Maybe date shouldn't be a full tab just a simple date widget (button?) on main properties tab opening a Gtk.Calendar when activated.

**Comment by gbtami** [comment]
Regarding 3. and 4. parsing tags is working in both case as you can see at https://github.com/pychess/pychess/blob/master/lib/pychess/Savers/pgn.py#L660 and https://github.com/pychess/pychess/blob/master/lib/pychess/Database/PgnImport.py#L456 respectively, but they are nor loaded to gamemodel nor saved to .sqlite at this moment. The former seems simpler to fix, the latter needs some more work.

Database/model.py has `tag` and `tag_game` tables not used for anything yet. The plan was to add some arbitrary tagging of database games later. (Something similar used in web blogs/twitter/etc.)
I think we can drop the `tag` table and reuse the `tag_game` table to store arbitrary .pgn header tags.
Instead of `tag_id` we just have to add `tag_name` and `tag_value` columns there.

Telling the truth I'm working on learning modules, so feel free to start working on 2. 3. 4. also.

**Comment by ecrucru** [comment]
After testing your latest changes, everything looks all right to me.
It was a harder work than expected, but the result is very nice.
Thanks a lot.

**Comment by gbtami** [comment]
One more thing I'm thinking about is to remove "Annotator" and add "Result" as a radio button instead on main tags tab. Then if users want to digitalise they own OTB game its enough to enter pure moves in "Enter game notation" dialogue then fill the tags in "Properties" dialogue.

**Comment by ecrucru** [comment]
Indeed, good idea !

For the result, I would see a drop-down list with human-readable texts instead of a collection of checkboxes labelled like filterDialog. Or at least, they should be spaced out more.

By the way, I noted two other little things related to the visual aspect :
- calling gameinfoDialog should set the first tab active by default (the window doesn't appear to be destroyed but just hidden)
- there is no black border for the tag editor, while there is one for engineDialog

**Comment by ecrucru** [comment]
@gbtami : there is a little regression in the handling of `Result`. Indeed, if you play a local game, then edit the properties of the game (ex. change the names), then continue to play, the main line becomes a subline.

**Comment by ecrucru** [comment]
Thanks for the fix
