### ISSUE TITLE
Using end games

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1585]
Hello,

1) Knowing that my PyChess' configuration has been cleared (removed hidden files), how could we start an endgame from the welcome screen ? The button 'Learn' is grayed. For now, I should start a puzzle, close the puzzle to get access to the view.

2) Is it possible to exclude some endgames obviously loosing ? For example, if the static eval returns more than 15cp, then another position is searched. I take for example `KPP vs kp`.

3) The dock panels are rather disorganized at the first run. Is that normal ?

```
|   |
| P | Practice!
| a |- - - - - -
| n | Panel
| e |- - - - - -
| l | Panel
|   |- - - - - -
|   | Panel
```

4) What about custom combinations for the positions ?

Tell me if/how you prefer this issue to be splitted.

Thank you.

**Comment by gbtami** [comment]
1. You can start learn perspective clicking on the big book icon next to the left of "Puzzle:" label. Maybe we should add two combo instead of one. One for category (lecture/lesson/endgame/puzzle) and one for actual selected item of that category.

2. "obviously" depends on your playing strength, but you are right we need something better here :) All initial endgame positions are created random now. Only positions starting with possible capture are dropped. We should study how FICS/ICC endgamebot creates reasonable position. Any suggestion is welcome!

3. Learn perspective initial layout is not organized at all yet. And "Prectice!" panel is waiting for implementation also. I can imagine some simple cumulative progress status there.

4. If you mean to let the user create custom piece combinations, then yes. We should create some simple GUI solution to implement what on FICS is "tell endgamebot play kqqkqrp" for example.

All in all, there is nothing in stone in pychess learning stuff yet. My vision with this is to provide something similar what is available on FICS/ICC/Lichess, but offline. 

Some random TODO:
Endgames now uses stockfish to play with, but it would be better to use local/online tablebases instead if there is at least one is available.
https://syzygy-tables.info/apidoc should be implemented next to https://github.com/pychess/pychess/blob/master/lib/pychess/Utils/lutils/egtb_k4it.py
Interactive lessons hints are not implemented at all yet.

**Comment by gbtami** [comment]
@ecrucru created https://github.com/pychess/pychess/projects/1 with new issues listed above. Let see how this github project thing can help organizing our future work :)

**Comment by ecrucru** [comment]
OK, thanks for the splitted issues.
Fyi, the dashboard seems to be in read-only.

**Comment by gbtami** [comment]
Can I change it somewhere?

**Comment by ecrucru** [comment]
After a test done yesterday, it seems possible only to people with write access to the repository.
