### ISSUE TITLE
Bypass the limit of 100 games in database

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1613]
Hello,

This is a feature request.

If you open a PGN file, you are allowed to display only the first 100 games. I assume that it intends to speed up the display and reduce the memory footprint. However, there is no way to explore the rest of the file either by filtering it with unknown criteria : who are the players ? what is the date ? what is the ELO ? what is the town ? The content of the file is mysterious if you download it from the Internet. So many games are not reachable easily.

Setting the limit in the preferences could be nice. May it be also possible to load the next N games if the scrollbar of the list of games reaches the bottom ?

Regards

**Comment by gbtami** [comment]
The first/backward/ forward buttons below the game list is there to load first/prev/next 100 games to the list. Are they not working for you?

**Comment by ecrucru** [comment]
The unobtrusive buttons are nice. The initial question is messy with this useful information in mind. Sorry for this very late discovery.

It is not rare to get some PGN files having thousands of games. So after a recheck, the primary need remains to be able to have this limit of 100 as a custom parameter.

To go further with the navigation bar, can we :
- add something telling the number of pages ?
- add a field to jump to a given page ? Toggling the filter sends the player back to the first page
- not go to the next page if the current page is not full ?

Thanks

**Comment by gbtami** [comment]
Unfortunately pychess database query/filter handling is not integrated to the level compared to scid/chessbase. PyChess uses .pgn as database storage backend, and creates sqlite db only for header tag filtering, chess_db index (basically a polyglot .bin) to exact position filtering, and scoutfish index file (containing parsed movetext information in binary format used by stockfish codebase to replay them on the fly and determine if given position is matching given query) to sophisticated queries. This 3 tool knows nothing about each other contrast to scid/chessbase, where the integrated chess engine is integral part of his database engine.

Maybe adding a combobox next to navigation buttons with some predefined parameters (100,500/1000, etc.) something similar used on web database apps may help here?

1. We can tell number of pages only if no scoutfish filter applied, because scoutfist filtering creates results on demand.
2. Same problem as 1.
3. You can navigate in current game list using the scrollbar or with pgup/pgdn keys. I agree that database navigation should be better regarding UI/UX. (At least adding tooltip text to navigation buttons would be nice.)
