### ISSUE TITLE
Replay/Reset one lesson

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1688]
Hello,

Once a lesson is finished, it cannot be replayed.

Is it possible to reset an individual progression (instead of everything), or allow to replay a completed lesson ?

Thanks

**Comment by gbtami** [comment]
No reset for individual progression was implemented yet, but it would be useful.
You can replay completed lessons if you open Learn perspective and double click on a selected lesson row.

**Comment by ecrucru** [comment]
Oh sorry, initially, I wanted to say "puzzle" instead of "lesson" :

![image](https://user-images.githubusercontent.com/24614488/46765354-152f6100-ccdf-11e8-8bf1-3b33d9819f67.png)

I finally found that error :
```
Traceback (most recent call last):
  File "/pychess/lib/pychess/perspectives/learn/PuzzlesPanel.py", line 115, in row_activated
    start_puzzle_from(filename)
  File "/pychess/lib/pychess/perspectives/learn/PuzzlesPanel.py", line 131, in start_puzzle_from
    index = progress.index(0)
ValueError: 0 is not in list
```

LessonPanel is written like PuzzlePanel, so the issue is there also :

```
Traceback (most recent call last):
  File "/pychess/lib/pychess/perspectives/learn/LessonsPanel.py", line 100, in row_activated
    start_lesson_from(filename)
  File "/pychess/lib/pychess/perspectives/learn/LessonsPanel.py", line 112, in start_lesson_from
    index = progress.index(0)
ValueError: 0 is not in list
```

Thanks

**Comment by gbtami** [comment]
I think we should add a new "Reset button" to each row next to the progress bars and rename the existing all in one to "Reset all my progress" or something similar.

**Comment by gbtami** [comment]
Fixed above errors in https://github.com/pychess/pychess/commit/e45a6cb9b6b88402a1e6f0c71671039b6446b8db

**Comment by mathieucaroff** [comment]
Hello, I'm a student (with [@Bracewind](https://github.com/Bracewind)). I'm interested in adding this "Reset one lesson" feature.

### Feature definition

@gbtami said:

> I think we should add a new "Reset button" to each row next to the progress bars and rename the existing all in one to "Reset all my progress" or something similar.

I agree. I think it might be nicer to have a "Show per-lesson reset buttons" checkbox. It would be unticked by default, so that the individual reset buttons are not visible by default. That checkbox's state would be temporary, lost when the application is closed, possibly lost when leaving the lesson view.

I'm not sure where to put that checkbox. My first idea was below the "Reset all my progress" button. Now I think it might be relevant to put it in the "View" menu.

The current "Reset all lessons" has a confirmation alert (a modal). I think the single-lesson "Reset" button should have a confirmation alert too.

* Should the text of the tickbox be "Show per-lesson reset buttons"?
  * ... given that it's also going to be used for resetting the puzzles.
* Where should the checkbox be put? (if it matters)
* Should there be a modal on the "Reset" button?

### Translation

I'm not sure how to do with the translations.

- Is it okay to just create a new entry `_("Reset")` without putting it in (all) the .po files?

### Implementation

#### GUI

I looked a bit into it. We are going to need something like `renderer = CellRendererButton()` (in `lib/pychess/perspectives/learn/PuzzlesPanel.py`). I found some doc for PyGtk (see [about `CellRenderer`s](https://python-gtk-3-tutorial.readthedocs.io/en/latest/cellrenderers.html)) here. We could either use a `Gtk.CellRendererPixbuf` or subclass Gtk.CellRenderer to create a `CellRendererButton`, that would contain a `Gtk.Button`.

I don't have experience with Gtk (I think neither of us 5 students do), so I'm not sure how to receive the clicks if using `Gtk.CellRendererPixbuf`s. I'vs read a post suggesting doing it at the TreeView level.

* Should I rather use a `Gtk.CellRendererPixbuf` or make subclass? (if you have an opinion)
  * If using a `CellRendererPixbuf`, any advice about how to receive the click event?

#### Internally

The progression is represented by a dictionary (filename -> progression list) pairs.
It's easy enough to derive a single-lesson reset from the exiting global reset function:

> `lib/pychess/perspectives/learn/__init__.py`:`138-150`
> 
> ```py
> def on_reset_clicked(button):
>     dialog = Gtk.MessageDialog(mainwindow(), 0, Gtk.MessageType.QUESTION,
>                                 Gtk.ButtonsType.OK_CANCEL,
>                                 _("You will lose all your progress data!"))
>     response = dialog.run()
>     if response == Gtk.ResponseType.OK:
>         for filename, progress in lessons_solving_progress.items():
>             lessons_solving_progress[filename] = [0] * len(progress)
>         for filename, progress in puzzles_solving_progress.items():
>             puzzles_solving_progress[filename] = [0] * len(progress)
>         self.update_progress(None, None, None)
>     dialog.destroy()
> ```

### Gtk documentation / help

I'm not sure where to find reference documentation and other reliable resources about PyGObject and PyGtk.

**Comment by gbtami** [comment]
I don't think  "Show per-lesson reset buttons" checkbox is needed. Just add "Reset" buttons after progress bars. You can read the relevant doc here https://lazka.github.io/pgi-docs/#RB-3.0/classes/CellRendererPixbuf.html#RB.CellRendererPixbuf

Regarding translations _("Reset") is enough. pychess.pot is updated by create_template.po.sh (Triggered by me from time to time.)
Then transifex grabs this and merges it with individual .po files at https://www.transifex.com/gbtami/pychess/ for translators.

**Comment by mathieucaroff** [comment]
PR #1793 does not include resetting the lessons, only the puzzles. I plan to do the lessons in a later PR, after #1793 is accepted.

**Comment by mathieucaroff** [comment]
I have opened two topics on the Gtk's Discourse forum.

## Putting buttons in the rows

https://discourse.gnome.org/t/cellrendererbutton-have-a-clickable-button-in-a-treeview-column/2103

Interestingly, we are recommended to switch from a GtkTreeView to GtkListBox. In this PR however, I've opted for the simpler option of using a CellRendererPixbuf.

## Controlling the auto-sizing behavior of columns in TreeViews

https://discourse.gnome.org/t/treeview-column-auto-sizing-behaviour/2112

If the forum yields a solution, I'll probably include it in the PR #1793.

**Comment by gbtami** [comment]
Not a big issue but maybe you should disable reset (or just do nothing) when progress is already on 0.

**Comment by mathieucaroff** [comment]
PR #1794 is very small.

I'll have a bigger PR coming right after #1794 to disable the reset button when progress is 0.
