### ISSUE TITLE
.sqlite files are accumulating - can they be deleted automatically?

### ISSUE THREAD

**Issue by loug42** [pychess/pychess#1729]
sorry - comment added by mistake...

**Comment by loug42** [comment]
I have been deleting these sqlite files as they accumulate.  I don't seem to need them and wonder if they can be removed automatically (or not created at all).

**Comment by gbtami** [comment]
.sqlite, .scout, .bin files are all created to help .pgn database search/filter tasks. You can delete them when pychess is not running without any problem, but they will be recreated next time you open a .pgn
Automatic deletion may be problematic, because creating them on huge .pgn files can take long time.
