### ISSUE TITLE
Remove Time Limit

### ISSUE THREAD

**Issue by TheChymera** [pychess/pychess#1772]
When I try to play against the engine, I get a countdown of 5 minutes. What that actually means, is that I can't play for longer than 5 minutes, since the engine moves almost instantaneously. How can I disable this?

**Comment by gbtami** [comment]
Instead of pushing the "Start game" button, you can click on the big weather (sun, clouud, etc.) on the left of "Your color" and "Opponent". That will open a new game dialog where you can choose different time controls.

Another solution. You can get this from menu also:
Game -> New game -> From default position
