### ISSUE TITLE
Configure animation speed

### ISSUE THREAD

**Issue by radiomix** [pychess/pychess#1779]
I have installed package `pychess 0.12.2-1` on Ubuntu 16.04 and I a am very happy with it. 
Playing against an engine IMO the animation speed of the board while the engine moves is too fast. 
I saw the constant `ANIMATION_TIME = 0.5` is set to a fixed value in 
in https://github.com/pychess/pychess/blob/069b1854bd50f7e1cd148d715b987c6c980a1e1e/lib/pychess/widgets/BoardView.py#131
After changing it manually to `30`  the pieces move smoothly. 

Is there a way to make this value configurable?
And could `ANIMATION_TIME` be extended to animating the arrows too?

Regards

Michael

**Comment by gbtami** [comment]
0.12.2 is rather old. Try latest PyChess release from https://github.com/pychess/pychess/releases please! Read https://github.com/pychess/pychess/blob/master/INSTALL for dependencies needed.
Unfortunately Debian/Ubuntu official packages seems abandoned :(

I have not added new features to PyChess long time, because I started a new project https://github.com/gbtami/pychess-variants
But I'm maintaining PyChess yet, so any contribution is welcome.

**Comment by radiomix** [comment]
Hi Bajusz,

after updating to the more recent version `Steinitz 1.0.0` I am quite happy with the animation speed.
Thank you for checking.

Michael
