### ISSUE TITLE
Adding a new engine issue

### ISSUE THREAD

**Issue by pelican74** [pychess/pychess#1872]
When trying to add a new engine (mine), PyChess complains that my binary "does not seem correct"
I have the problem on W10 with 1.0.0 and on Ubuntu with 1.0.2-1
What checks are done by PyChess when adding an engine that I may fail ? My engine talks uci (subset of).
(As a test, I overwrote with my binary one of the PyChess preconfigured engines (stockfish_10_x32...), and this works perfectly well. So PyChess can launch and talk to my engine without problem, it's really adding it that it does not like)

**Comment by ecrucru** [comment]
Hello @pelican74

This bug is solved by #1848 but it is not part of an active release yet.

A way to solve your issue is to patch your installed copy of PyChess. The 4 added lines of code affect the files `engineNest.py` and `command.py` (see the previous link for the details).

Else in your engine, don't use relative paths and call these lines:

```c
setbuf(stdin, NULL);
setbuf(stdout, NULL);
```

HTH
