### ISSUE TITLE
pychess not working on Ubuntu 21.10 (Gnome 40)

### ISSUE THREAD

**Issue by felso** [pychess/pychess#1922]
$ pychess
/usr/games/pychess:17: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk
Failed to create splash screen
ERROR: Not all dependencies installed! You can find them in INSTALL
Namespace Gdk is already loaded with version 4.0

**Comment by gbtami** [comment]
Do you have all the dependencies installed?

**Comment by felso** [comment]
Yes. But I now think the problem is in the Debian package. I was actually able to run it from the source.

**Comment by gbtami** [comment]
.deb from https://github.com/pychess/pychess/releases should work.

**Comment by felso** [comment]
That worked perfectly. Thank you.

**Comment by andre-caldas** [comment]
So... the fix is:
- Do not install from Debian???

Do we not care if it does not work in Debian? There is no need to find out why it does not work in Debian?

**Comment by gbtami** [comment]
Debian/Ubuntu packages are outdated. They ship 1.0.0 released in 2019. Our latest release is 1.0.3!
If they don't want to ship latest software, I can do nothing but provide .deb releases in pychess github repo.
I'm not a Debian developer/packager, sry.

**Comment by andre-caldas** [comment]
Yes, but you are ignoring a bug!
If an exception is trown, `splash` is not initialized/defined.
https://github.com/pychess/pychess/blob/6f0e1b881dd52e9ef6bcfaaa1e18cfd7f5304e77/pychess#L20

But then, it is referred here:
https://github.com/pychess/pychess/blob/6f0e1b881dd52e9ef6bcfaaa1e18cfd7f5304e77/pychess#L246

One big advantage of free software, is that it works in so many environments that the whole process makes it very robust. If you ignore problems because someone else has built it, you loose this advantage.

**Comment by andre-caldas** [comment]
Bug reported to Debian packaging system:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1014202

By the way, the bug was fixed here:
https://github.com/pychess/pychess/commit/e6091ea11ef4164c9cf14180d782eecba1b6bfcc
