### ISSUE TITLE
Typo in close dialog box

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#322]
Original [issue 322](https://code.google.com/p/pychess/issues/detail?id=322) reported by [teohhanhui](https://code.google.com/u/113513569782580480814/) 2008-04-29

**What steps will reproduce the problem?**
1. Create a new game.
2. Play.
3. Close the game.

**What is the expected output? What do you see instead?**
"Save the current game before you close it?

It is not possible later to continue the game, if do don't save it."

"...if do don't save it." should be "if you don't save it."

**Does it happen every time?**
Yes.

**What version of the product are you using?**
Philidor 0.8.1

Did you use an installed version of PyChess or did you run in from a
tarball/svn?
Installed.

**Please provide any additional information below.**
N/A

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=322#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-05-21

Thanks for your report. This is however fixed in the released 0.8.2.
(Although the fix of this bug has resulted in the particularly string not being
translated into any languages :$)

Cheers, Thomas
- changed status to: Invalid
