### ISSUE TITLE
Some icons not provided by gnome-icon-theme

### ISSUE THREAD

**Issue by ghost** [pychess/pychess#339]
Original [issue 339](https://code.google.com/p/pychess/issues/detail?id=339) reported by [michel.sylvan](https://code.google.com/u/106783242436572907187/) 2008-08-27

**What steps will reproduce the problem?**
1. Run pychess without echo-icon-theme (or any other icon theme that
provides icons modified in patch below)

**What is the expected output? What do you see instead?**
Should work; pychess claims dependency only on gnome-icon-theme

Note: In some places, pychess is already using an alternate icon set if the
stock_\* icons are not found; this just needs to be extended to cover the
places addressed in the patch.

Did you use an installed version of PyChess or did you run in from a
tarball/svn?
Installed

**Comment by pychess** [comment]
- attached [pychess-0.8.2-icons.patch](https://code.google.com/p/pychess/issues/detail?id=339#c0)

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=339#c1) posted by [lobais](https://code.google.com/u/lobais/) 2008-08-28

The main problem has been, that the stock_weather-storm icons are much nicer to look
at, than the weather-storm ones :)
I don't know if it is still the case. I'll take a look.
Thanks for the patch.
- changed status to: Accepted

**Comment by pychess** [comment]
Original [comment 2.](https://code.google.com/p/pychess/issues/detail?id=339#c2) posted by [michel.sylvan](https://code.google.com/u/106783242436572907187/) 2008-08-28

I'd be happy to add an additional dependency to the Fedora package, if you can
document where the stock_ icons are coming from.

As I mentioned earlier, the patch is not ideal -- you might want to do catch the
exception and substitute the icons. Actually, even better: load all the icons in one
place, say an "icons" module? that way people who want to customize pychess'
look-and-feel don't have to look at multiple places (well, they still need to look at
the Glade files. Updated patch that also fixes fics_logon.glade below).

Is FICS support functional? On my system, after a successful login, the interface
stops repainting itself. The only change I've made is to install the pychess data in
/usr/share/pychess rather than /usr/share/games/pychess, per Fedora packaging guidelines.
- attached [pychess-0.8.2-icons.patch](https://code.google.com/p/pychess/issues/detail?id=339#c2)

**Comment by pychess** [comment]
Original [comment 3.](https://code.google.com/p/pychess/issues/detail?id=339#c3) posted by [lobais](https://code.google.com/u/lobais/) 2008-09-17

Thanks, I'll look into implementing your patch. Also, an icon module sounds
appealing, even though it really shouldn't be nessesary with gtk, tango and all that.

The freeze might be fixed in trunk. It shouldn't be affected by install location at
least. By the way, why is there a /usr/share/games directory, if games are not
supposed to lie there?

**Comment by pychess** [comment]
Original [comment 4.](https://code.google.com/p/pychess/issues/detail?id=339#c4) posted by [michel.sylvan](https://code.google.com/u/106783242436572907187/) 2008-09-17

Ah, if the Tango icon set is a requirement, and pychess works fine if that's
installed, then we can drop the patch and document the requirement. It's just that
it's not installed by default on Fedora, so would be nice to explicitly declare the
dependency.

As for /usr/share/games, I have completely no idea why it's still there. Presumably a
relic from older file-system layouts -- or perhaps it's just Fedora's filesystem
layout guideline that disallows certain things that are in FHS. They're not too happy
about /opt and /srv in RPM packages either.

**Comment by pychess** [comment]
Original [comment 5.](https://code.google.com/p/pychess/issues/detail?id=339#c5) posted by [lobais](https://code.google.com/u/lobais/) 2008-09-20

If you don't have tango installed, can you test if it works with it? If it does, I'll
add a notice somewhere ;)

I'll just change standard directory to /usr/share then. Thanks.

**Comment by pychess** [comment]
Original [comment 6.](https://code.google.com/p/pychess/issues/detail?id=339#c6) posted by [lobais](https://code.google.com/u/lobais/) 2008-12-12

I've changed the requested icons. Can you check if there are any new ones causing
trouble?

**Comment by pychess** [comment]
Original [comment 7.](https://code.google.com/p/pychess/issues/detail?id=339#c7) posted by [lobais](https://code.google.com/u/lobais/) 2009-02-10
- changed status to: Need-Info

**Comment by pychess** [comment]
Original [comment 8.](https://code.google.com/p/pychess/issues/detail?id=339#c8) posted by [gbtami](https://code.google.com/u/gbtami/) 2013-04-21
- changed status to: Fixed
