### ISSUE TITLE
FICS chat channels are limited on pychess!

### ISSUE THREAD

**Issue by pychess** [pychess/pychess#934]
Original [issue 934](https://code.google.com/p/pychess/issues/detail?id=934) reported by [xatrickforge](https://code.google.com/u/107950337048345824018/) 2015-01-06

I want to be able to join channel 24...etc and talk there. Perhaps, you should allow pychess to join any channel number the user defines.

**Comment by pychess** [comment]
Original [comment 1.](https://code.google.com/p/pychess/issues/detail?id=934#c1) posted by [gbtami](https://code.google.com/u/gbtami/) 2015-01-07
- changed status to: Accepted
- added label: Enhancement

**Comment by cajone** [comment]
This has been implemented, I think the problem the user is experiencing is that channels that are in the more channels section of the conversation window are not numerically sorted but are character sorted.

If you look further down the list you will see channel 24 it probably just not where you expected it.

I think possibly the fix for this is to numerically sort the channels
