### ISSUE TITLE
auto call flag bug

### ISSUE THREAD

**Issue by gideon425** [pychess/pychess#955]
Using the pychess files from github, it appears that pychess ends the game if the player runs out of time.  I think this would be correct if Auto Call Flag is true.  However, the game also ends if Auto Call Flag is false.
If you already have a fix for this, are you likely to apply it soon?
If not, perhaps I should look at the issue and include it in the changes I am doing

**Comment by gbtami** [comment]
In what kind of games? Human, engine, fics?

**Comment by gideon425** [comment]
human vs engine. the human runs out of time

**Comment by gbtami** [comment]
I don't consider this bug. In engine-engine games autoflag is the usual default. Why don't claim engines clock when they play against human?

**Comment by ghost** [comment]
If I may comment on this as well, while it's true that engines are at a disadvantage since they can't actually claim the clock per protocol and it would make sense to automatically make them do it, in a human <-> engine game IMHO we should err on the side of the human since it's most likely a fun game of someone just trying to play some chess.

Therefore, while strictly "auto-flag" just describes pychess doing it in its role as a referee watching over the game, I would suggest considering that if turned off the engine also shouldn't flag in human vs engine (or pychess respectively for the engine) - there is no real feature loss since anyone who wants to play by the strict rules can simply enable auto-flag to ensure it happens.

I agree that's probably not strictly what the option originally meant, but it seems to make more sense to me from a gameplay/fun point of view to interpret this more leniently.

**Comment by gbtami** [comment]
I'm sold :) I will fix this.
